Detect the reason for known transaction error
Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":47,\"error\":{\"code\":-32000,\"message\":\"known transaction: 0751582b1725c78a78cf0ad16e01d64655f0b5f7a1cd577175b9313cb13872f6\"}}\n", error={"code":-32000}, requestBody="{\"method\":\"klay_sendRawTransaction\",\"params\":[\"0x08f885820123850ba43b7400827b0c94c40b6909eb7085590e1c26cb3becc25368e249e985174876e800940667dcd3dc0ad91120efb7d6fea506fda117cdddf847f8458207f6a0240f5869ad3e56165acd55fa2eb4adf83de72b67185b25839b397554ec3524b3a0019421f8a446a11b0e54a2f03159e9b2e29d02931171142a6890e9627a3898a6\"],\"id\":47,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://public-en-baobab.klaytn.net", code=SERVER_ERROR, version=web/5.7.1)